### PR TITLE
deb: include prerm script in debian package

### PR DESCRIPTION
**Pull request by Watson1978**
Add missing `prerm` script to include it in debian package

### CODE REVIEW

**Comment by daipom** [comment]
Thanks! But this should be merged to #713 because `prerm` is newly added there.

**Comment by Watson1978** [comment]
Thanks. Fixed

**Review by daipom — APPROVED** [review]
Thanks! LGTM!

**Review by daipom — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
