### PR TITLE
msi: migrate to "Fluent Package"

### PR DESCRIPTION
**Pull request by kenhys**
NOTE: need to consider renaming td-agent-gem.bat and td-agent.bat

TODO: follow up to  #461 need to tweak PR again.

### CODE REVIEW

**Comment by kenhys** [comment]
rebase after #461 was merged.

**Comment by ashie** [comment]
CI failed:
```
2023-05-16T04:22:04.6869797Z Errno::ENOENT: No such file or directory @ rb_sysopen - msi/assets/td-agent-prom
2023-05-16T04:22:04.6871026Z pt.bat
```

**Review by ashie — APPROVED** [review]
Note: These commands are mainly launched by users manually or automatically run by installer. So probably we don't need td-agent-* symlinks or shortcuts.

**Comment by ashie** [comment]
td-agen-version.bat might be still needed but we'll add it in another PR if it's really needed.

**Comment by ashie** [comment]
Thanks!

**Pull request merged**
