### PR TITLE
dmg: use compatible service name for config and socket

### PR DESCRIPTION
**Pull request by daipom**
To align with Linux service definition.

### CODE REVIEW

**Comment by daipom** [comment]
This will solve the failure of 

* #477

I'm testing it on my fork: https://github.com/daipom/fluent-package-builder/actions/runs/5063945296

**Comment by daipom** [comment]
> This will solve the failure of
> 
>     * [dmg: add install test #477](https://github.com/fluent/fluent-package-builder/pull/477)
> 
> 
> I'm testing it on my fork: https://github.com/daipom/fluent-package-builder/actions/runs/5063945296

Success!

**Comment by ashie** [comment]
Thanks!

**Comment by daipom** [comment]
Thanks for merging!

**Pull request merged**
