### PR TITLE
deb rpm: fix v4 migration with restarting service

### PR DESCRIPTION
**Pull request by kenhys**

### CODE REVIEW

**Comment by kenhys** [comment]
It might be lxd is a bit freaky?

**Comment by kenhys** [comment]
Changes against apt/systemd-test/*.sh is a workaround until /etc/needrestart/conf.d/ fix will be merged into.

**Comment by daipom** [comment]
Shouldn't we fix this on the master branch?

**Comment by kenhys** [comment]
TODO: re-target master branch.

**Pull request closed without merging**
