### PR TITLE
CI: Fix target branch for td-agent v4

### PR DESCRIPTION
**Pull request by ashie**

### CODE REVIEW

**Comment by ashie** [comment]
I tested it in my fork but still failed: https://github.com/ashie/fluent-package-builder/tree/td-agent-v4

**Comment by daipom** [comment]
Thanks for this fix.

Don't we need to specify the branch at `actions/checkout`?

```yml
- uses: actions/checkout@master
  with:
    ref: td-agent-v4
```

**Comment by ashie** [comment]
> I tested it in my fork but still failed: https://github.com/ashie/fluent-package-builder/tree/td-agent-v4

This is because I didn't push tags to my fork.
It's needed for package size test: https://github.com/fluent/fluent-package-builder/blob/33f482c8fdcc9ebb17ed6b03aa4211707ac6a64a/fluent-package/yum/pkgsize-test.sh#L21-L23

**Comment by ashie** [comment]
> Don't we need to specify the branch at `actions/checkout`?
> 
> ```yaml
> - uses: actions/checkout@master
>   with:
>     ref: td-agent-v4
> ```

It's performed against committed revision, so it's not needed in usual.

**Comment by daipom** [comment]
Oh, I see! Thanks!

**Pull request merged**
