### PR TITLE
apt: remove deprecated piuparts stuff

### PR DESCRIPTION
**Pull request by kenhys**
* xenial (16.04LTS) was already reached EOL.
   * do not skip piuparts for jammy (22.04)
   * use recent gnupg (old version is used for xenial, no
     need to do so)
   * remove unused bionic configuration
   * fix key verification failure of keyring path

### CODE REVIEW

**Comment by kenhys** [comment]
checking piuparts failure...

**Comment by kenhys** [comment]
rerun failed job.

**Comment by kenhys** [comment]
failure seems reproducible, check it...

**Comment by kenhys** [comment]
Checking with local bullseye container, piuparts succeeds. :thinking: 

```
0m7.2s DEBUG: Removed directory tree at /tmp/tmpbkpkl1yj
0m7.2s INFO: PASS: All tests.
0m7.2s INFO: piuparts run ends.
root@78c2bf2db24b:/# piuparts --distribution=bullseye --existing-chroot=/var/lib/chroot/bullseye-root --mirror="http://packages.treasuredata.com/4/debian/bullseye/ bullseye contrib"  --skip-logrotatefiles-test /tmp/fluent-package_5.0.0-1_amd64.deb
```

**Comment by kenhys** [comment]
It seems that as if no --priviledged is specified, but it is not true for bullseye.

```
E: Can not write log (Is /dev/pts mounted?) - posix_openpt (19: No such device)
```

**Comment by kenhys** [comment]
> E: Can not write log (Is /dev/pts mounted?) - posix_openpt (19: No such device)

It has nothing to do with piuparts error, it is reproducible on local environment.

**Comment by kenhys** [comment]
Observed different error  with: `piuparts --distribution=bullseye --existing-chroot=/var/lib/chroot/bullseye-root --mirror="http://packages.treasuredata.com/4/debian/bullseye/ bullseye contrib"  --skip-logrotatefiles-test /tmp/fluent-package_5.0.0-1_amd64.deb` on local.

```
0m9.3s DUMP: 
  diversion of /usr/share/man/man1/sh.1.gz to /usr/share/man/man1/sh.distrib.1.gz by dash
  diversion of /bin/sh to /bin/sh.distrib by dash
0m9.3s DEBUG: Command ok: ['chroot', '/tmp/tmpprjmxwpj', 'dpkg-divert', '--list']
0m9.3s DEBUG: Starting command: ['chroot', '/tmp/tmpprjmxwpj', 'apt-get', 'clean']
0m9.3s DEBUG: Command ok: ['chroot', '/tmp/tmpprjmxwpj', 'apt-get', 'clean']
0m9.3s DEBUG: Recording chroot state
0m9.5s ERROR: FAIL: After purging files have disappeared:
  /opt/	 owned by: fluent-package

0m9.5s ERROR: FAIL: Installation and purging test.
```

**Comment by kenhys** [comment]
The above failure is caused by the fallback of missing access to bullseye/contrib. :thinking:

**Review by ashie — APPROVED** [review]

**Comment by ashie** [comment]
Thanks!

**Pull request merged**
