### PR TITLE
ci deb: tweak downgrade test case

### PR DESCRIPTION
**Pull request by kenhys**
Now, no need to unmask td-agent because transitional td-agent package was installed before.

As unmask fluentd is not enough to cleanup td-agent inactive(dead) link so explicitly disable it to purge them.

### CODE REVIEW

**Comment by kenhys** [comment]
checking why...

**Comment by kenhys** [comment]
check this issue in forked repository.

**Comment by kenhys** [comment]
It seems that inactive (dead) link (td-agent.service => /lib/systemd/system/fluentd.service )blocks to enable service when re-installing td-agent.

**Comment by kenhys** [comment]
Without this fix, td-agent.service points inactive(removed) file (/lib/systemd/system/fluentd.service.)
As a result, systemd can't find service correctly and fails to start it.

<details>
<summary>failure log</summary>
```
+ debug_service_files 'DEBUG: after downgrade'
  + echo DEBUG: after downgrade
  + set +e
  DEBUG: after downgrade
  + ls -la /usr/lib/systemd/system/
  + grep -E 'td-agent|fluent-package'
  -rw-r--r--  1 root root  1098 Nov 22  2023 td-agent.service
  + ls -la /etc/systemd/system
  + ls -la /usr/lib/systemd/system/multi-user.target.wants/
  total 96
  drwxr-xr-x 18 root root 4096 Nov 12 08:37 .
  drwxr-xr-x  5 root root 4096 Aug 21 21:40 ..
  drwxr-xr-x  2 root root 4096 Aug 21 21:42 cloud-final.service.wants
  drwxr-xr-x  2 root root 4096 Aug 21 21:42 cloud-init.target.wants
  lrwxrwxrwx  1 root root   40 Aug 21 21:42 dbus-org.freedesktop.ModemManager1.service -> /lib/systemd/system/ModemManager.service
  lrwxrwxrwx  1 root root   44 Aug 21 21:40 dbus-org.freedesktop.resolve1.service -> /lib/systemd/system/systemd-resolved.service
  lrwxrwxrwx  1 root root   45 Aug 21 21:40 dbus-org.freedesktop.timesync1.service -> /lib/systemd/system/systemd-timesyncd.service
  drwxr-xr-x  2 root root 4096 Aug 21 21:40 default.target.wants
  drwxr-xr-x  2 root root 4096 Aug 21 21:42 final.target.wants
  drwxr-xr-x  2 root root 4096 Aug 21 21:40 getty.target.wants
  drwxr-xr-x  2 root root 4096 Aug 21 21:42 graphical.target.wants
  lrwxrwxrwx  1 root root   38 Aug 21 21:42 iscsi.service -> /lib/systemd/system/open-iscsi.service
  drwxr-xr-x  2 root root 4096 Aug 21 21:42 mdmonitor.service.wants
  drwxr-xr-x  2 root root 4096 Nov 12 08:37 multi-user.target.wants
  lrwxrwxrwx  1 root root   38 Aug 21 21:42 multipath-tools.service -> /lib/systemd/system/multipathd.service
  drwxr-xr-x  2 root root 4096 Aug 21 21:40 network-online.target.wants
  drwxr-xr-x  2 root root 4096 Aug 21 21:42 open-vm-tools.service.requires
  drwxr-xr-x  2 root root 4096 Aug 21 21:42 paths.target.wants
  -rw-r--r--  1 root root  343 Nov 12 08:36 snap-core20-2318.mount
  -rw-r--r--  1 root root  337 Nov 12 08:36 snap-lxd-29619.mount
  -rw-r--r--  1 root root  343 Nov 12 08:36 snap-snapd-21759.mount
  -rw-r--r--  1 root root  467 Aug 21 21:43 snap.lxd.activate.service
  -rw-r--r--  1 root root  541 Aug 21 21:43 snap.lxd.daemon.service
  -rw-r--r--  1 root root  330 Aug 21 21:43 snap.lxd.daemon.unix.socket
  drwxr-xr-x  2 root root 4096 Aug 21 21:43 snapd.mounts.target.wants
  drwxr-xr-x  2 root root 4096 Nov 12 08:36 sockets.target.wants
  drwxr-xr-x  2 root root 4096 Aug 21 21:42 sshd-keygen@.service.d
  lrwxrwxrwx  1 root root   31 Aug 21 21:42 sshd.service -> /lib/systemd/system/ssh.service
  drwxr-xr-x  2 root root 4096 Aug 21 21:42 sysinit.target.wants
  lrwxrwxrwx  1 root root   35 Aug 21 21:41 syslog.service -> /lib/systemd/system/rsyslog.service
  lrwxrwxrwx  1 root root   35 Nov 12 08:37 td-agent.service -> /lib/systemd/system/fluentd.service
  drwxr-xr-x  2 root root 4096 Aug 21 21:42 timers.target.wants
  lrwxrwxrwx  1 root root   41 Aug 21 21:42 vmtoolsd.service -> /lib/systemd/system/open-vm-tools.service
  + set -e
  + systemctl status --no-pager fluentd
  total 24
  drwxr-xr-x  2 root root  4096 Aug 21 21:41 .
  drwxr-xr-x 24 root root 20480 Nov 12 08:37 ..
  lrwxrwxrwx  1 root root    15 Oct 25  2022 dbus.service -> ../dbus.service
  lrwxrwxrwx  1 root root    15 Nov 21  2023 getty.target -> ../getty.target
  lrwxrwxrwx  1 root root    29 Nov  2  2020 plymouth-quit-wait.service -> ../plymouth-quit-wait.service
  lrwxrwxrwx  1 root root    24 Nov  2  2020 plymouth-quit.service -> ../plymouth-quit.service
  lrwxrwxrwx  1 root root    33 Nov 21  2023 systemd-ask-password-wall.path -> ../systemd-ask-password-wall.path
  lrwxrwxrwx  1 root root    25 Nov 21  2023 systemd-logind.service -> ../systemd-logind.service
  lrwxrwxrwx  1 root root    39 Nov 21  2023 systemd-update-utmp-runlevel.service -> ../systemd-update-utmp-runlevel.service
  lrwxrwxrwx  1 root root    32 Nov 21  2023 systemd-user-sessions.service -> ../systemd-user-sessions.service
  Unit fluentd.service could not be found.
  + systemctl status --no-pager td-agent
  Unit td-agent.service could not be found.
```
</details>

**Review by daipom — APPROVED** [review]
LGTM. Thanks!

**Comment by daipom** [comment]
Note: we need to fix broken RPM tests in another PR.

**Pull request merged**
