### PR TITLE
deb: rpm: add test for update future ver with v4 compat

### PR DESCRIPTION
**Pull request by daipom**

### CODE REVIEW

**Comment by daipom** [comment]
This test should fail for now.
We need to fix this.

**Comment by daipom** [comment]
Rebased to the latest master to apply:

* #551

**Comment by daipom** [comment]
Checking yum tests on my fork too: https://github.com/daipom/fluent-package-builder/actions/runs/5676841531

**Comment by daipom** [comment]
deb tests should still fail.

**Comment by daipom** [comment]
Rebased to the latest master to apply:

* #553

**Comment by daipom** [comment]
Now the tests should succeed.
Waiting the results...

**Comment by daipom** [comment]
All yum tests succeed in my fork (without serverspec test): https://github.com/daipom/fluent-package-builder/actions/runs/5676841531/job/15384694516

**Comment by daipom** [comment]
All deb tests succeed too.

**Review by kenhys — APPROVED** [review]
LGTM.

**Comment by daipom** [comment]
Thanks for your review!

**Pull request merged**
