### PR TITLE
deb rpm: use latest install script

### PR DESCRIPTION
**Pull request by kenhys**
As install script for fluent-package had been deployed, we will switch to it.

### CODE REVIEW

**Comment by kenhys** [comment]
I've forgot to follow amazon specific issue, so updated again.

**Comment by kenhys** [comment]
waiting CI....

**Comment by kenhys** [comment]
Fixed a syntax error.

**Comment by kenhys** [comment]
The changed part is working expectedlly.

**Review by daipom — APPROVED** [review]
LGTM. Thanks.
Rerunning CI...

**Pull request merged**
