### PR TITLE
Delete TD_AGENT_OPTIONS at td-agent.service

### PR DESCRIPTION
**Pull request by kuroponzu**
Fix: https://github.com/fluent-plugins-nursery/fluent-package-builder/issues/352

### CODE REVIEW

**Review by ashie — APPROVED** [review]

**Comment by ashie** [comment]
Thanks!

**Review by ashie — CHANGES_REQUESTED** [review]
Sorry, now I've noticed that we still need it for RPM.
`EnvironmentFile` for RPM systems is `/etc/sysconfig/td-agent` but it's not provided by the package.

**Comment by kuroponzu** [comment]
Sorry for the late reply. I understand.
Should I take the following steps?
- In rpm environment, modify the following code and create `/etc/sysconfig/td-agent`.
  - https://github.com/fluent/fluent-package-builder/blob/83cd35c210904d8c7b8b763c2a91a7fbc21b2078/td-agent/Rakefile#L549-L554
- In deb environment, modify the following code and create `/etc/default/td-agent`.
  - https://github.com/fluent/fluent-package-builder/blob/83cd35c210904d8c7b8b763c2a91a7fbc21b2078/td-agent/Rakefile#L563-L568
- Delete the following code.
  - https://github.com/fluent/fluent-package-builder/blob/1b2699c15ca018ced6fcfc9c85c77832f6b68149/td-agent/templates/package-scripts/td-agent/deb/postinst#L47-L54
  - refs: https://github.com/fluent/fluent-package-builder/pull/353#pullrequestreview-855408587
  - > In addition, /etc/default/td-agent should be provided as a package file, should not be generated by postinst script.

**Comment by kenhys** [comment]
@kuroponzu 

Yes, as you commented,  it is good steps to do it.

**Comment by kuroponzu** [comment]
@kenhys @ashie 
Fix it!

**Comment by kenhys** [comment]
@kuroponzu could you follow the DCO?

image

**Comment by kuroponzu** [comment]
@kenhys 
I have finished to follow the DCO!

**Comment by kenhys** [comment]
Thanks, @kuroponzu 

New config file will not be installed explicitly to /etc/sysconfig/td-agent, so td-agent/yum/td-agent.spec.in must be updated, too

td-agent/yum/td-agent.spec.in %files section.

```
%config(noreplace) %{_sysconfdir}/sysconfig/@PACKAGE@
```

**Comment by kenhys** [comment]
Then, /etc/default/td-agent also should be installed.

**Comment by ashie** [comment]
We'll merge this in 4.4.0, skip 4.3.1 to keep compatibility.

**Review by ashie — APPROVED** [review]
LGTM

I'm sorry for my late response, and thanks for your contribution!

**Pull request merged**
