### PR TITLE
msi: stop customizing icons for file browser

### PR DESCRIPTION
**Pull request by daipom**
We should use the default wix icons for these.

### CODE REVIEW

**Comment by daipom** [comment]
2023-05-18_15h58_24

before

2023-05-18_16h20_47

after

2023-05-18_15h58_09

**Comment by ashie** [comment]
😱

**Review by ashie — APPROVED** [review]

**Comment by ashie** [comment]
Thanks!

**Comment by daipom** [comment]
Thanks!

**Pull request merged**
