### PR TITLE
Stop maintaining multiple copies of the same conf

### PR DESCRIPTION
**Pull request by daipom**
Just refactoring. This does not change the result.

### CODE REVIEW

**Comment by daipom** [comment]
We need to do some fixes following this.
I will do them after this PR.

* Update the Fluentd config for Windows.
* Update the following filepaths.
  * `/opt/fluent/share/td-agent.conf.tmpl`
    * I think the filename should be `fluentd.conf.default`.
  * `/opt/fluent/share/td-agent-ruby.conf`

I have one question.
Do we still need `/opt/fluent/share/td-agent.conf.tmpl`?

It is not used after the following PR:

* #344

but it is still better to have the default config under the `/opt/fluent/share/`, right?

**Comment by daipom** [comment]
Note: related fixes in the past:

* #344
* #147
* #101
* #3

**Comment by ashie** [comment]
> but it is still better to have the default config under the /opt/fluent/share/, right?

I think so.

**Comment by daipom** [comment]
> > but it is still better to have the default config under the /opt/fluent/share/, right?
> 
> I think so.

Thanks!

**Review by kenhys — APPROVED** [review]
As the rest of the work will be done in another PR (https://github.com/fluent/fluent-package-builder/pull/525#issuecomment-1638221669),
it seems a reasonable fix.

**Comment by daipom** [comment]
Thanks for your review!

**Comment by daipom** [comment]
Done all TODO!

https://github.com/fluent/fluent-package-builder/pull/525#issuecomment-1638221669

**Pull request merged**
