### PR TITLE
ci: add update tests about service status

### PR DESCRIPTION
**Pull request by daipom**
There is specification difference between DEB and RPM.

At least, there should be tests to clarify the current specification.

The current specification:

* DEB
  * The service is **enabled** by default.
  * The service **starts automatically after new install**.
  * The service starts automatically **when it was active OR enabled before update**.
* RPM
  * The service is **disabled** by default.
  * The service **does not start automatically after new install**.
  * The service starts automatically **only when it was active before update**.

### CODE REVIEW

**Comment by daipom** [comment]
Rebased to the latest master.

**Comment by daipom** [comment]
I have refactored the codes.
Confirming CI...

**Review by Watson1978 — APPROVED** [review]
👍🏻

**Review by kenhys — APPROVED** [review]
LGTM.

**Comment by daipom** [comment]
Thanks for your review!

**Pull request merged**
