### PR TITLE
Use out_secondary_file for secondary output

### PR DESCRIPTION
**Pull request by daipom**
To solve the warning message:

    Use different plugin for secondary ...

### CODE REVIEW

**Comment by daipom** [comment]
This will change the output path as follows:

* before: `/var/log/td-agent/failed_records_0.log`
* after: `/var/log/td-agent/failed_records/dump.bin.0`

If this change is unacceptable, then we should not make this change.

**Comment by daipom** [comment]
> This will change the output path as follows:
> 
>     * before: `/var/log/td-agent/failed_records_0.log`
> 
>     * after: `/var/log/td-agent/failed_records/dump.bin.0`
> 
> 
> If this change is unacceptable, then we should not make this change.

Note: `out_secondary_file` can't output the files with the same format as `out_file`.
Even if we use `base_name` as follows,  the path will be like `/var/log/td-agent/failed_records.0`.

```xml
    <secondary>
      @type secondary_file
      directory /var/log/td-agent
      basename failed_records
    </secondary>
```

**Review by ashie — APPROVED** [review]
Since the next release is major update, so it's good timing to change.

**Review by ashie — CHANGES_REQUESTED** [review]
Sorry, I forgot to point out a thing.
Could you modify also fluent-package/templates/opt/fluent/share/td-agent.conf.tmpl?

**Comment by daipom** [comment]
Oh, sorry. We need to fix it too. Thanks for your review.
I will fix it and confirm the behavior on each platform.

**Comment by daipom** [comment]
* Waiting #525

**Comment by daipom** [comment]
* Rebased to the latest master to include #525

**Comment by daipom** [comment]
> Sorry, I forgot to point out a thing. Could you modify also fluent-package/templates/opt/fluent/share/td-agent.conf.tmpl?

By #525, we don't need to manage `td-agent.conf.tmpl` anymore.
I will check the package default behavior in some platforms after the CI completed

**Comment by daipom** [comment]
Rebased to solve conflicts.

**Review by ashie — APPROVED** [review]

**Comment by daipom** [comment]
I confirmed the actual logs of msi and rpm.
In addition, I added the tests for each platform to confirm the log files.

**Review by ashie — APPROVED** [review]

**Comment by ashie** [comment]
Thanks!

**Comment by daipom** [comment]
Thanks for your review!

**Pull request merged**
