### PR TITLE
Use new path for fluent-package

### PR DESCRIPTION
**Pull request by kenhys**
No need to use old path for fluent-package.

### CODE REVIEW

**Comment by kenhys** [comment]
Need to rebase with #499

**Comment by kenhys** [comment]
failure on focal and jammy. checking....

**Comment by daipom** [comment]
It sometimes fails in other PRs as well. (#501)

Is it possible that https://github.com/fluent/fluent-package-builder/pull/489#issuecomment-1587075397 problem still remains?

**Comment by kenhys** [comment]
> Is it possible that [#489 (comment)](https://github.com/fluent/fluent-package-builder/pull/489#issuecomment-1587075397) problem still remains?

There is a possibility of it. checking...

**Comment by kenhys** [comment]
Try to run the failed job again.

**Comment by kenhys** [comment]
I'm doubt that this fragile behavior comes from running systemctl immediately. (The state of current status is not synced yet) 
maybe waiting appropriate time will work. :thinking:

**Comment by daipom** [comment]
> I'm doubt that this fragile behavior comes from running systemctl immediately. (The state of current status is not synced yet) maybe waiting appropriate time will work. thinking

I wonder if this is the real cause of this problem.

I have tested the following 2 patterns on my local.

* Add `sleep 3` before `systemctl status` check like this PR.
* Add `--wait` option to `systemctl status` check.

However, both patterns fail about 1 in 3 times.

It may be a good idea to add `sleep` or `--wait` option just in case, but perhaps it has nothing to do with this problem.

**Review by daipom — APPROVED** [review]
I reran tests several times and confirmed they can still fail.
However, I think it has nothing to do with this PR.

This PR looks good to me.

**Comment by kenhys** [comment]
> However, both patterns fail about 1 in 3 times.

Thank you for checking.
I'll investigate it again.

Anyway, using `--wait` option is better, I'll fix it.

**Comment by kenhys** [comment]
changed to use `--wait` option to sync.

**Pull request merged**
