### PR TITLE
Try to add centos-stream-9

### PR DESCRIPTION
**Pull request by ashie**

### CODE REVIEW

**Comment by cosmo0920** [comment]
For using binary compatible containers, I recommend to use [almalinux 9 container](https://hub.docker.com/_/almalinux) or [ubi9 container](https://catalog.redhat.com/software/containers/ubi9/618326f8c0d15aff4912fe0b) for building RHEL/CentOS 9 packages. RockyLinux 9 is still not released yet.
CentOS Stream 9 does not have same packages to CentOS 9.

**Comment by hrw** [comment]
There is no such thing as CentOS 9 - only CentOS Stream 9.

**Comment by cosmo0920** [comment]
We need to fix installation test failure: https://github.com/fluent/fluent-package-builder/runs/6770953843?check_suite_focus=true#step:7:28
Also, we have to use `--enablerepo=crb` instead of `--enablerepo=powertools` in installation test script.

**Comment by ashie** [comment]
> For using binary compatible containers, I recommend to use [almalinux 9 container](https://hub.docker.com/_/almalinux) or [ubi9 container](https://catalog.redhat.com/software/containers/ubi9/618326f8c0d15aff4912fe0b) for building RHEL/CentOS 9 packages. RockyLinux 9 container is still not released yet. CentOS Stream 9 does not have same packages to CentOS 9.

Oh, I didn't know almalinux 9 container is already published. Thanks!

To tell the truth, I already tried ubi9 container at first.
But I'm not sure the license agreement whether we can use it on GitHub Actions (with RedHat developer account to retrieve required packages), this is the why I use CentOS Stream 9 in this pull request.

**Comment by hrw** [comment]
Can someone rerun it?

Local run:
```
Wrote: /root/rpmbuild/SRPMS/td-agent-4.3.1.1-1.el9.src.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/td-agent-debugsource-4.3.1.1-1.el9.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/td-agent-debuginfo-4.3.1.1-1.el9.x86_64.rpm
Wrote: /root/rpmbuild/RPMS/x86_64/td-agent-4.3.1.1-1.el9.x86_64.rpm
```

**Comment by ashie** [comment]
In addition, 6d12cb1e44cf3593fee018251d29db7b74cf3206 includes unexpected changes in Gemfile.lock.

**Comment by ashie** [comment]
For trying AlmaLinux 9: #399

**Pull request closed without merging**
