### PR TITLE
Add v5.1.0

### PR DESCRIPTION
**Pull request by kenhys**

### CODE REVIEW

**Comment by kenhys** [comment]
Observed that package size was increased. 

OLD: 11.96 MiB (12544584) : fluent-package_5.0.4-1_amd64.deb
NEW: 16.61 MiB (17421184) : fluent-package/apt/repositories/debian/pool/bullseye/main/f/fluent-package/fluent-package_5.1.0-1_amd64.deb

**Comment by kenhys** [comment]
follow nokogiri 1.16.7.

**Comment by kenhys** [comment]
After #661 was merged, rebase with it.

**Comment by kenhys** [comment]
Accidentally, windows build fails. :sob:

**Review by daipom — APPROVED** [review]
LGTM!
Thanks!

**Pull request merged**
