### PR TITLE
Migrate TD_AGENT_ prefix to FLUENT_PACKAGE_

### PR DESCRIPTION
**Pull request by kenhys**
TODO: fluent-package/msi/assets/fluentd.bat must be fixed after c:\opt\td-agent migration. #494

### CODE REVIEW

**Comment by daipom** [comment]
Rebased to the latest master.

**Comment by daipom** [comment]
I have added a fix: 87fcb2713c57fe1d3772217b337ce5919248aff1

This replacement is done to the new `/etc/default/fluentd`, so the replacement source must be `FLUENT_PACKAGE_LOG_FILE`, not `TD_AGENT_LOG_FILE`.

Now, waiting CI...

**Review by daipom — APPROVED** [review]
All green!
LGTM! Thanks!

**Comment by daipom** [comment]
> TODO: fluent-package/msi/assets/fluentd.bat must be fixed after c:\opt\td-agent migration. #494

@kenhys Is this already done, right?

**Comment by kenhys** [comment]
> @kenhys Is this already done, right?

already done via #484.

**Pull request merged**
