### PR TITLE
dmg: Support Apple Silicon

### LINKED ISSUE #415: MacOS M1 builds not working
Hi,

I'm getting issues on deploying td-agent 4.1.x on MacOS m1 computers. Here is the error I get once installed:
```
/opt/td-agent/lib/ruby/2.7.0/yaml.rb:3: warning: It seems your ruby installation is missing psych (for YAML output).
    To eliminate this warning, please install libyaml and reinstall your ruby.
    /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': dlopen(/opt/td-agent/lib/ruby/2.7.0/x86_64-darwin20/psych.bundle, 0x0009): Library not loaded: '/usr/local/opt/libyaml/lib/libyaml-0.2.dylib' (LoadError)
      Referenced from: '/opt/td-agent/lib/ruby/2.7.0/x86_64-darwin20/psych.bundle'
      Reason: tried: '/usr/local/opt/libyaml/lib/libyaml-0.2.dylib' (no such file), '/usr/local/lib/libyaml-0.2.dylib' (no such file), '/usr/lib/libyaml-0.2.dylib' (no such file) - /opt/td-agent/lib/ruby/2.7.0/x86_64-darwin20/psych.bundle
    	from /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
    	from /opt/td-agent/lib/ruby/2.7.0/psych.rb:13:in `<top (required)>'
    	from /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
    	from /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
    	from /opt/td-agent/lib/ruby/2.7.0/yaml.rb:4:in `<top (required)>'
    	from /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
    	from /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
    	from /opt/td-agent/lib/ruby/2.7.0/rubygems.rb:715:in `load_yaml'
    	from /opt/td-agent/lib/ruby/2.7.0/rubygems/config_file.rb:332:in `load_file'
    	from /opt/td-agent/lib/ruby/2.7.0/rubygems/config_file.rb:182:in `initialize'
    	from /opt/td-agent/lib/ruby/2.7.0/rubygems/gem_runner.rb:79:in `new'
    	from /opt/td-agent/lib/ruby/2.7.0/rubygems/gem_runner.rb:79:in `do_configuration'
    	from /opt/td-agent/lib/ruby/2.7.0/rubygems/gem_runner.rb:44:in `run'
    	from /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.15.1/bin/fluent-gem:6:in `<top (required)>'
    	from /opt/td-agent/bin/fluent-gem:23:in `load'
    	from /opt/td-agent/bin/fluent-gem:23:in `<main>'
    package not found: fluent-plugin-macos-log
```

With the above, I tried to build the `.dmg` file from a M1 device but without any success. The process fails and complains that openssl is not found. Here is the output:
```bash
making encs
make[1]: Nothing to be done for `encs'.
./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems -r./arm64-darwin21-fake ./tool/rbinstall.rb --make="/Library/Developer/CommandLineTools/usr/bin/make" --dest-dir="/Users/ec2-user/fluent-package-builder/td-agent/staging" --extout=".ext" --mflags="- --jobserver-fds=4,5 -j" --make-flags=" --jobserver-fds=4,5 -j -- DESTDIR=/Users/ec2-user/fluent-package-builder/td-agent/staging" --data-mode=0644 --prog-mode=0755 --installed-list .installed.list --mantype="doc" --exclude=doc
installing binary commands:         /opt/td-agent/bin
installing base libraries:          /opt/td-agent/lib
installing arch files:              /opt/td-agent/lib/ruby/2.7.0/arm64-darwin21
installing pkgconfig data:          /opt/td-agent/lib/pkgconfig
installing extension objects:       /opt/td-agent/lib/ruby/2.7.0/arm64-darwin21
installing extension objects:       /opt/td-agent/lib/ruby/site_ruby/2.7.0/arm64-darwin21
installing extension objects:       /opt/td-agent/lib/ruby/vendor_ruby/2.7.0/arm64-darwin21
installing extension headers:       /opt/td-agent/include/ruby-2.7.0/arm64-darwin21
installing extension scripts:       /opt/td-agent/lib/ruby/2.7.0
installing extension scripts:       /opt/td-agent/lib/ruby/site_ruby/2.7.0
installing extension scripts:       /opt/td-agent/lib/ruby/vendor_ruby/2.7.0
installing extension headers:       /opt/td-agent/include/ruby-2.7.0/ruby
installing command scripts:         /opt/td-agent/bin
installing library scripts:         /opt/td-agent/lib/ruby/2.7.0
installing common headers:          /opt/td-agent/include/ruby-2.7.0
installing manpages:                /opt/td-agent/share/man (man1, man5)
installing default gems from lib:   /opt/td-agent/lib/ruby/gems/2.7.0 (build_info, cache, doc, extensions, gems, specifications)
                                    benchmark 0.1.0
Traceback (most recent call last):
	11: from ./tool/rbinstall.rb:947:in `<main>'
	10: from ./tool/rbinstall.rb:947:in `each'
	 9: from ./tool/rbinstall.rb:950:in `block in <main>'
	 8: from ./tool/rbinstall.rb:799:in `block in <main>'
	 7: from ./tool/rbinstall.rb:835:in `install_default_gem'
	 6: from ./tool/rbinstall.rb:835:in `each'
	 5: from ./tool/rbinstall.rb:845:in `block in install_default_gem'
	 4: from ./tool/rbinstall.rb:279:in `open_for_install'
	 3: from ./tool/rbinstall.rb:846:in `block (2 levels) in install_default_gem'
	 2: from /Users/ec2-user/fluent-package-builder/td-agent/downloads/ruby-2.7.6/lib/rubygems/specification.rb:2430:in `to_ruby'
	 1: from /Users/ec2-user/fluent-package-builder/td-agent/downloads/ruby-2.7.6/lib/rubygems/core_ext/kernel_require.rb:83:in `require'
/Users/ec2-user/fluent-package-builder/td-agent/downloads/ruby-2.7.6/lib/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- openssl (LoadError)
```

Here is some information on the device used for the build
```bash
Software:

    System Software Overview:

      System Version: macOS 12.4 (21F79)
      Kernel Version: Darwin 21.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      User Name: ec2-user (ec2-user)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 2:29

Hardware:

    Hardware Overview:

      Model Name: Mac mini
      Model Identifier: Macmini9,1
      Chip: Apple M1
      Total Number of Cores: 8 (4 performance and 4 efficiency)
      Memory: 16 GB
      System Firmware Version: 7459.121.3
      OS Loader Version: 7459.121.3
      Serial Number (system): H2WH325LQ6NY
      Hardware UUID: 27E95555-852B-5DE9-A1EC-DA011D1E1165
      Provisioning UDID: 00008103-0010282821FB001E
      Activation Lock Status: Disabled
```

I tried tweaking the command line with paths for the openssl binary/libraries but it did not work. Any idea on how we can solve this?

### PR DESCRIPTION
**Pull request by ashie**
* Enable to build Apple Silicon binary of OpenSSL
* Update prerequisites for macOS

Fix #415

### CODE REVIEW

**Comment by ashie** [comment]
Still something wrong.
Built gems aren't installed by this installer.

**Comment by ashie** [comment]
> Still something wrong. Built gems aren't installed by this installer.

It was my local environment fault.
Broken .bundle/config was remained.
After I cleaned up my local directory, I succeeded to create valid installer.

**Comment by daipom** [comment]
Thanks! I will see this tonight!

**Review by daipom — APPROVED** [review]
I succeeded in building td-agent on my M1 macbook!
LGTM.

**Comment by ashie** [comment]
Thanks!

**Comment by dferreiralopessc** [comment]
@ashie @daipom many thanks for your help on this. I've tested the build myself and it does work :heart: !

**Comment by ashie** [comment]
Thanks for your verification. Please let me know if you have any problem.
I'm going to pubish an experimental apple silicon binary.

**Pull request merged**
