### PR TITLE
dmg: add install test

### PR DESCRIPTION
**Pull request by daipom**

### CODE REVIEW

**Comment by daipom** [comment]
I confirmed this test succeeds in v4.5.0.

* https://github.com/daipom/fluent-package-builder/commit/f7ec49c158c86d210e9a8efb5e4e3460b5f1be8d
* https://github.com/daipom/fluent-package-builder/actions/runs/5055729469

**Comment by daipom** [comment]
Currently, Fluentd fails to start up with `256` ExitStatus. (without any logs)

```console
$ sudo launchctl load  /Library/LaunchDaemons/fluentd.plist
$ sudo launchctl list fluent-package
{
	"LimitLoadToSessionType" = "System";
	"Label" = "fluent-package";
	"OnDemand" = false;
	"LastExitStatus" = 256;
	"Program" = "/opt/fluent/usr/sbin/fluentd";
	"ProgramArguments" = (
		"/opt/fluent/usr/sbin/fluentd";
		"--log";
		"/var/log/td-agent/fluentd.log";
		"--use-v1-config";
	);
};
```

**Comment by daipom** [comment]
I will rebase this.

**Comment by daipom** [comment]
Now these tests must succeed.

**Comment by daipom** [comment]
> Now these tests must succeed.

Success!

**Comment by ashie** [comment]
Thanks!

**Comment by daipom** [comment]
Thanks!

**Pull request merged**
