### PR TITLE
rpm: enable AlmaLinux 9 test case

### PR DESCRIPTION
**Pull request by kenhys**
Note that confluent-community-2.13 seems signed by deprecated SHA-1.

https://www.redhat.com/en/blog/rhel-security-sha-1-package-signatures-distrusted-rhel-9

### CODE REVIEW

**Comment by kenhys** [comment]
TODO: need to investigate further more.

**Comment by kenhys** [comment]
It seems only v5 repository is affected.

**Comment by kenhys** [comment]
Checked size from repository metadata:

https://s3.amazonaws.com/packages.treasuredata.com/5/redhat/7/x86_64/repodata/3e541c385c3a293ff3be055df1da2678c6287992fa6948eb414d0b864bd14ee2-primary.xml.gz

```
<size package="15732116" installed="67864236" archive="69693560"/>
```

Fetched rpm:

```
$ ls -la fluent-package-5.0.0-1.el7.x86_64.rpm 
-rw-rw-r--. 1 vagrant vagrant 15730900 Aug  2 07:32 fluent-package-5.0.0-1.el7.x86_64.rpm
```

It seems that there is a mismatch of pkg size...

**Comment by kenhys** [comment]
It seems that rpm repository metadata is broken, so I've recreated again.

**Comment by kenhys** [comment]
now enabled test case has passed on almalinux9.

**Comment by kenhys** [comment]
image

**Comment by kenhys** [comment]
Removed redundant changes.

waiting CI...

**Review by daipom — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
