### PR TITLE
Add script to check manually installed plugin

### PR DESCRIPTION
**Pull request by kenhys**
Examples:

  Preinstalled plugins: (bundled by default)

   * fluent-plugin-calyptia-monitoring
   * fluent-plugin-concat ...

   * fluent-plugin-utmpx
   * fluent-plugin-webhdfs

  Currently Installed Plugins:

   * fluent-plugin-calyptia-monitoring
   * fluent-plugin-elasticsearch ...
   * fluent-plugin-utmpx
   * fluent-plugin-webhdfs

  Manually Installed Plugins:

   * fluent-plugin-concat

### CODE REVIEW

**Comment by daipom** [comment]
Wow! Thanks!

**Comment by kenhys** [comment]
found that it needs to be fixed on deb platform.

**Comment by daipom** [comment]
> found that it needs to be fixed on deb platform.
> 
> ```
> /opt/fluent/lib/ruby/3.2.0/bundler.rb:310:in `rescue in root':  (Bundler::Dsl::DSLError)
> [!] There was an error parsing `Gemfile`: Could not locate Gemfile or .bundle/ directory. Bundler cannot continue.
> 
>  #  from /opt/fluent/share/Gemfile:5
>  #  -------------------------------------------
>  #  
>  >  source "https://rubygems.org"
>  #  
> ```
> 
> 🤔

It seems that we need `BUNDLE_GEMFILE` environmental variable so that Bundler can find Gemfile.

```
ENV["BUNDLE_GEMFILE"] = ...
```

**Comment by kenhys** [comment]
> It seems that we need BUNDLE_GEMFILE environmental variable so that Bundler can find Gemfile.

Thanks!

**Comment by kenhys** [comment]
Once script was deployed for a package, when fluent-diagtool was implemented such a feature, it is hard to remove it in point view of compatibility, so keep it aside.

**Pull request closed without merging**
